web:
    build: .
    ports:
        - "4000:4000"
    environment:
        - DB_URL=mysql://root@db/FindFolks
    volumes:
        - ./:/opt/:ro
    links:
        - db

db:
    image: mysql
    environment:
        - MYSQL_DATABASE=FindFolks
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
        - ./db/:/docker-entrypoint-initdb.d/:ro
